<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mmlx</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>MMLX</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@(import|extends)\b</string>
			<key>name</key>
			<string>storage.mmlx</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(@[a-z-]{3,}[a-z\-0-9]+)\b</string>
			<key>name</key>
			<string>storage.mmlx.instrument</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@end\b</string>
			<key>name</key>
			<string>storage.mmlx.instrument</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>;</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\/\*</string>
			<key>end</key>
			<string>\*\/</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.mml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(#(TITLE|COMPOSER|PROGRAMER|MAKER|OCTAVE-REV|GATE-DENOM|INCLUDE|EX-DISKFM|EX-NAMCO106|EX-VRC6|EX-VRC7|EX-MMC5|EX-FME7|BANK-CHANGE|EFFECT-INCLUDE|NO-BANKSWITCH|AUTO-BANKSWITCH|BANK-CHANGE|SETBANK|DPCM-RESTSTOP|PITCH-CORRECTION|X-ABSOLUTE-NOTES|X-TRANSPOSE|X-COUNTER|X-TEMPO|X-SMOOTH))\b(.*)\n</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(SD)[0-9]+</string>
			<key>name</key>
			<string>keyword.command</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(SDOF)</string>
			<key>name</key>
			<string>keyword.command</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(N106|FDS|VRC6|VRC7)-([A-Z]+)\b</string>
			<key>name</key>
			<string>keyword.mml.voice</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[A-Z]+\b</string>
			<key>name</key>
			<string>keyword.mml.voice</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(o|l|q)[0-9]+\b</string>
			<key>name</key>
			<string>support.variable</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(w|r)[0-9]+\b</string>
			<key>name</key>
			<string>support.rest</string>
		</dict>
		<dict>
			<key>begin</key>
			<string> (t)([0-9]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\b</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(volume|timbre|adsr|max_volume|pitch|arpeggio|vibrato|q|chip|waveform|buffer): {0,}\|? {0,}(-)?([0-9]+)?(N106$|FDS$|VRC6$|VRC7$)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\b</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>( |\]|\:|\|)([0-9]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\]|\b)</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>( |\:|\|)(-)([0-9]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\]|\b)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[=&gt;&lt;\^\.\+]</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>/-/s</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^([a-zA-Z0-9\-_]+):( {0,})</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.instrument</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mmlx</string>
	<key>uuid</key>
	<string>E90ADC42-15D0-44A8-8664-E9ABF70E453E</string>
</dict>
</plist>
